version: "3.8"

services:
  web:
    image: nginx
    container_name: webserver
    networks:
      - security_net

  attacker:
    image: kalilinux/kali-rolling
    container_name: attacker
    tty: true
    volumes:
      - ./attacker:/attacker
    networks:
      - security_net

  suricata:
    image: jasonish/suricata
    container_name: suricata
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_NICE
    command: -i eth0 -S /var/lib/suricata/rules/suricata.rules
    network_mode: service:web
    volumes:
      - ./suricata/logs:/var/log/suricata
      - ./suricata_conf/suricata.rules:/var/lib/suricata/rules/suricata.rules

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - security_net
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - security_net
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.11.0
    container_name: filebeat
    user: root
    command: filebeat -e -strict.perms=false
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./suricata/logs:/var/log/suricata:ro
    networks:
      - security_net
    depends_on:
      - elasticsearch
      - suricata

networks:
  security_net:
    driver: bridge
